export const products = [
  {
    id: 1,
    name: "Попугай",
    age: "1 месяц",
    price: 15000,
    description: "Бело-синий попугай.",
    availability: true,
    image: "https://i.ibb.co/tpFMmB7W/image.jpg",
    category: "bird",
  },
  {
    id: 2, 
    name: "Канарейка",
    age: "3 месяца",
    price: 1400,
    description: "Желтая канарейка.",
    availability: true,
    image: "https://i.ibb.co/TD7tZ4fq/image.jpg",
    category: "bird",
  },
  {
    id: 3,
    name: "Тукан",
    age: "2 месяца",
    price: 90000,
    description: "Белогрудый тукан..",
    availability: true,
    image: "https://i.ibb.co/xKdc90NN/image.jpg",
    category: "bird",
  },
  {
    id: 4,
    name: "Козодой",
    age: "3 недели",
    price: 500000,
    description: "Исполинский козодой.",
    availability: true,
    image: "https://i.ibb.co/CpcYTQZX/image.jpg",
    category: "bird",
  },
  {
    id: 5,
    name: "Хорек",
    age: "2 месяца",
    price: 20000,
    description: "Домашний хорек.",
    availability: true,
    image: "https://i.ibb.co/n8kjMpCG/image.jpg",
    category: "small",
  },
  {
    id: 6,
    name: "Выдра",
    age: "2 месяца",
    price: 25000,
    description: "Домашняя выдра.",
    availability: true,
    image: "https://i.ibb.co/8L0bcLmp/image.jpg",
    category: "small",
  }
];
