export const products = [
  {
    id: 1,
    name: "Попугай",
    age: "1 месяц",
    price: 15000,
    description: "Бело-синий попугай.",
    availability: true,
    image: "/images/popugai.jpg",
    category: "bird",
  },
  {
    id: 2, 
    name: "Канарейка",
    age: "3 месяца",
    price: 1400,
    description: "Желтая канарейка.",
    availability: true,
    image: "/images/kanareyka.jpg",
    category: "bird",
  },
  {
    id: 3,
    name: "Тукан",
    age: "2 месяца",
    price: 90000,
    description: "Белогрудый тукан.",
    availability: true,
    image: "/images/tukan.jpg",
    category: "bird",
  },
  {
    id: 4,
    name: "Козодой",
    age: "3 недели",
    price: 500000,
    description: "Исполинский козодой.",
    availability: true,
    image: "/images/kozodoy.jpg",
    category: "bird",
  },
  {
    id: 5,
    name: "Хорек",
    age: "2 месяца",
    price: 20000,
    description: "Домашний хорек.",
    availability: true,
    image: "/images/horek.jpg",
    category: "small",
  },
  {
    id: 6,
    name: "Выдра",
    age: "2 месяца",
    price: 25000,
    description: "Домашняя выдра.",
    availability: true,
    image: "/images/vydra.jpg",
    category: "small",
  }
];